---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: ansible

  roles:
    - common
    - web
    - db

#- name: configure and deploy the webservers and application code
#  hosts: linux
#  remote_user: ansible
#
#  roles:
#    - web
#
#- name: deploy MySQL and configure the databases
#  hosts: linux
#  remote_user: ansible
#
#  roles:
#    - db

